sudo: required

dist: bionic


before_install:
  - sudo apt install curl gnupg
  - curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
  - echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
  - sudo apt update && sudo apt install bazel-1.0.0

before_script: sh ./setup_opencv.sh

cache:
  directories:
    - /usr/lib/
    - /usr/include/


jobs:
  include:
    - stage: Bazel build
      script: sh ./build.sh
